apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: pbak
  annotations:
    serving.knative.dev/creator: "ArgoCD"
    serving.knative.dev/lastModifier: "ArgoCD"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: colour
        app.kubernetes.io/instance: {{ .Values.name }}
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: dmetzler/web-color@sha256:913be5f9930bbbde778c109a91a80eb1f6990dce8d25916a41fcf92c3be7a9d5
          imagePullPolicy: Always
          name: color
          ports:
            - containerPort: 8000
          env:
            - name: COLOR
              value: {{ .Values.color }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
              